import type { CurriculumPack } from '../types/curriculum';
import { buildDaysFromDrafts, ref } from './dayFactory';

const RK = 'https://www.ruankao.org.cn/';
const MOHRSS = 'https://www.mohrss.gov.cn/';

/**
 * Soft exam (信息系统项目管理师) preparation pack.
 */
export const examGaoxiangPack: CurriculumPack = {
  id: 'exam-ruankao-gaoxiang',
  version: '1.1.0',
  title: '软考高项备考 23 课',
  subtitle: '选择 · 案例 · 论文 · 门禁模考',
  category: 'exam',
  locale: 'zh-CN',
  supportedPersonTypes: [
    'working_professional',
    'exam_sprinter',
    'college_student',
    'career_switcher',
  ],
  summary:
    '共 23 课，按连续日历日推进。面向信息系统项目管理师的压缩备考包，强调真题、采分点与真实项目论文素材。',
  optionalTracks: ['side'],
  phases: [
    { id: 'H1', name: '筑基', goal: '知识域地图', gateId: 'G1' },
    { id: 'H2', name: '刷题', goal: '选择案例稳定', gateId: 'G2' },
    { id: 'H3', name: '论文冲刺', goal: '三篇限时稿', gateId: 'G3' },
  ],
  days: buildDaysFromDrafts([
    {
      phaseId: 'H1',
      phaseName: '筑基',
      week: 1,
      title: '确认大纲与资料清单',
      estimatedMinutes: 40,
      content:
        '核对当年大纲版本，备齐官方教程/真题来源/错题本。明确考试窗口与报名监视，避免资料版本错误导致无效投入。',
      path: ['打开软考官网', '记录大纲年份', '列出资料清单', '建立错题本文件'],
      references: [ref('软考官网', RK), ref('人社部', MOHRSS)],
      acceptanceCriteria: ['资料清单齐全', '错题本已建'],
      acceptanceTests: [
        ['e1', '目标考季？', '说出'],
        ['e2', '教材版本依据？', '大纲年份'],
        ['e3', '真题覆盖多少年？', '建议≥8'],
      ],
      deliverable: '资料清单',
      minimumMode: true,
    },
    {
      phaseId: 'H1',
      phaseName: '筑基',
      week: 1,
      title: '十大知识域总导图',
      estimatedMinutes: 55,
      content:
        '用一张图串起整体/范围/进度/成本/质量/资源/沟通/风险/采购/干系人，并映射到你真实项目会用到的动作。',
      path: ['阅读教程目录', '画总导图', '标注弱域', '写工作映射 5 条'],
      references: [ref('软考官网', RK)],
      acceptanceCriteria: ['导图完整', '弱域已标'],
      acceptanceTests: [
        ['e4', '十大域能否背出？', '可'],
        ['e5', '你的最弱域？', '指出'],
        ['e6', '举一个项目映射', '具体'],
      ],
      deliverable: '知识域导图',
      minimumMode: true,
    },
    {
      phaseId: 'H1',
      phaseName: '筑基',
      week: 1,
      title: '进度与网络图计算专项',
      estimatedMinutes: 70,
      content:
        '专项歼灭关键路径、时差、压缩手段。每天至少 8 题，直到看见数字就能动手，避免案例场算崩。',
      path: ['复习公式卡', '做网络图 8 题', '总结错因', '重做错题'],
      references: [ref('软考官网', RK)],
      acceptanceCriteria: ['完成 8 题', '错因分类'],
      acceptanceTests: [
        ['e7', '关键路径定义？', '正确'],
        ['e8', '总时差含义？', '正确'],
        ['e9', '今日正确率？', '如实'],
      ],
      deliverable: '计算专项记录',
      track: 'practice',
    },
    {
      phaseId: 'H1',
      phaseName: '筑基',
      week: 1,
      title: '挣值管理 PV/EV/AC 专项',
      estimatedMinutes: 70,
      content:
        '熟练 CPI/SPI/EAC 等常用公式与解读话术，能把「进度落后但成本节约」类题讲清楚。',
      path: ['背公式卡', '做 10 道挣值题', '写解读模板', '错题入库'],
      references: [ref('软考官网', RK)],
      acceptanceCriteria: ['10 题完成', '解读模板成文'],
      acceptanceTests: [
        ['e10', 'CPI 公式？', 'EV/AC'],
        ['e11', 'SPI<1 意味着？', '进度落后'],
        ['e12', 'EAC 常见算法？', '能说一种'],
      ],
      deliverable: '挣值专项卷',
      track: 'practice',
      minimumMode: true,
    },
    {
      phaseId: 'H1',
      phaseName: '筑基',
      week: 1,
      title: '项目素材卡 ×3（论文原料）',
      estimatedMinutes: 60,
      content:
        '用真实项目填写三张素材卡：背景、角色、问题、措施、结果数字。禁止假项目；数字不够就缩小真实范围。',
      path: ['复制模板×3', '每卡填 2 个度量', '标注可映射知识域', '脱敏检查'],
      references: [ref('软考官网', RK)],
      acceptanceCriteria: ['三卡有数字', '无虚构关键事实'],
      acceptanceTests: [
        ['e13', '口述一卡 90 秒', '含问题措施数字'],
        ['e14', '哪张偏进度？', '指出'],
        ['e15', '哪张偏风险？', '指出'],
      ],
      deliverable: '素材卡×3',
      requireEvidence: true,
      minimumMode: true,
    },
    {
      phaseId: 'H1',
      phaseName: '筑基',
      week: 1,
      title: '门禁 G1：筑基验收',
      track: 'gate',
      gateId: 'G1',
      estimatedMinutes: 50,
      content:
        '证明你具备进入刷题期的基础：导图、计算专项、素材卡齐全。缺证据不得过门禁。',
      path: ['汇总产物清单', '补薄弱项', '填写证据', '制定刷题周计划'],
      references: [ref('软考官网', RK)],
      acceptanceCriteria: ['三类产物齐', '证据非空'],
      acceptanceTests: [
        ['g1a', '弱域是？', '说出'],
        ['g1b', '素材卡路径？', '写出'],
        {
          id: 'g1c',
          question: '下周每日刷题分钟数（打字）',
          passHint: '数字',
          requiresTypedAnswer: true,
        },
      ],
      deliverable: 'G1 记录',
      requireEvidence: true,
      minimumMode: true,
    },
    {
      phaseId: 'H2',
      phaseName: '刷题',
      week: 2,
      title: '选择真题套卷 1（不限时诊断）',
      estimatedMinutes: 90,
      content:
        '先不限时摸清弱域分布，建立考点统计表，而不是追求分数面子。诊断后只回炉高频错章。',
      path: ['完成 1 套选择', '统计错域', '写入错题本', '定回炉顺序'],
      references: [ref('软考官网', RK)],
      acceptanceCriteria: ['套卷完成', '错域统计存在'],
      acceptanceTests: [
        ['e16', '得分？', '如实'],
        ['e17', 'Top 错域？', '指出'],
        ['e18', '回炉第一章？', '指出'],
      ],
      deliverable: '套卷1记录',
      track: 'practice',
      requireEvidence: true,
    },
    {
      phaseId: 'H2',
      phaseName: '刷题',
      week: 2,
      title: '选择真题套卷 2（限时）',
      estimatedMinutes: 90,
      content:
        '按考试节奏限时完成，训练取舍。目标是稳定接近及格线趋势，而不是偶尔超常发挥。',
      path: ['限时作答', '对答案', '错题二刷', '更新趋势表'],
      references: [ref('软考官网', RK)],
      acceptanceCriteria: ['限时完成', '趋势表更新'],
      acceptanceTests: [
        ['e19', '是否超时？', '是/否'],
        ['e20', '相对套卷1变化？', '升/降'],
        ['e21', '仍反复错的点？', '列出'],
      ],
      deliverable: '套卷2记录',
      track: 'practice',
    },
    {
      phaseId: 'H2',
      phaseName: '刷题',
      week: 2,
      title: '案例：进度延误与变更',
      estimatedMinutes: 75,
      content:
        '练习案例条列采分点：先写 1.2.3 要点再展开。聚焦进度延误、范围蔓延、变更控制三类高频。',
      path: ['精做进度案例 2 题', '精做变更案例 2 题', '总结答法模板', '对照参考答案补点'],
      references: [ref('软考官网', RK)],
      acceptanceCriteria: ['4 题完成', '模板成文'],
      acceptanceTests: [
        ['e22', '范围蔓延第一句怎么答？', '变更/基线'],
        ['e23', '进度压缩两种？', '赶工/快速跟进等'],
        ['e24', '今天采分点习惯？', '先条列'],
      ],
      deliverable: '案例答卷A',
      track: 'practice',
      minimumMode: true,
    },
    {
      phaseId: 'H2',
      phaseName: '刷题',
      week: 2,
      title: '案例：成本风险质量',
      estimatedMinutes: 75,
      content:
        '覆盖成本超支、风险爆发、质量事故答法，强调原因分类与纠偏措施要可执行，避免空喊口号。',
      path: ['成本案例 2 题', '风险案例 2 题', '质量案例 1 题', '错因归类'],
      references: [ref('软考官网', RK)],
      acceptanceCriteria: ['5 题完成', '错因表更新'],
      acceptanceTests: [
        ['e25', '挣值在案例怎么用？', '能说'],
        ['e26', '风险应对四策略？', '可列举'],
        ['e27', '质量预防vs检查？', '能区分'],
      ],
      deliverable: '案例答卷B',
      track: 'practice',
    },
    {
      phaseId: 'H2',
      phaseName: '刷题',
      week: 2,
      title: '加餐：错题本结构化（可选）',
      track: 'side',
      estimatedMinutes: 35,
      content:
        '可选侧支：把错题本改成「考点→错因→正确话术」三列，方便考前快刷。冲刺模式可隐藏；有余力时强烈建议做。',
      path: ['建三列表头', '迁移≥15 条错题', '每条写正确话术', '标高频标签'],
      references: [ref('软考官网', RK)],
      acceptanceCriteria: ['≥15 条结构化', '有高频标签'],
      acceptanceTests: [
        ['es1', '三列是什么？', '考点错因话术'],
        ['es2', '迁移了几条？', '数字'],
        ['es3', '一个高频标签？', '有'],
      ],
      deliverable: '结构化错题本',
    },
    {
      phaseId: 'H2',
      phaseName: '刷题',
      week: 2,
      title: '门禁 G2：选择+案例趋势验收',
      track: 'gate',
      gateId: 'G2',
      estimatedMinutes: 50,
      content:
        '用两套选择与两份案例证明你进入论文期资格。若选择远低于及格趋势，应延长刷题而非硬写论文。',
      path: ['汇总趋势表', '决定是否进入论文', '补最弱 1 域', '提交证据'],
      references: [ref('软考官网', RK)],
      acceptanceCriteria: ['趋势表完整', '进/缓决策明确'],
      acceptanceTests: [
        ['g2a', '选择趋势是否接近 45？', '是/否'],
        ['g2b', '最弱域？', '指出'],
        {
          id: 'g2c',
          question: '是否进入论文期（是/缓）打字',
          passHint: '是或缓',
          requiresTypedAnswer: true,
        },
      ],
      deliverable: 'G2 记录',
      requireEvidence: true,
      minimumMode: true,
    },
    {
      phaseId: 'H3',
      phaseName: '论文冲刺',
      week: 3,
      title: '论文结构模板（只背结构不背全文）',
      estimatedMinutes: 50,
      content:
        '固化摘要、背景、子标题、效果、不足的结构。子标题必须绑定题目关键词，避免百科式堆过程名。',
      path: ['写出通用提纲', '准备进度/风险/质量三套子标题', '限时 20 分钟列提纲', '找空洞处'],
      references: [ref('软考官网', RK)],
      acceptanceCriteria: ['三套子标题齐', '提纲可复用'],
      acceptanceTests: [
        ['e28', '进度论文子标题？', '能列'],
        ['e29', '风险论文子标题？', '能列'],
        ['e30', '如何防空话？', '动作+数字'],
      ],
      deliverable: '提纲库',
      minimumMode: true,
    },
    {
      phaseId: 'H3',
      phaseName: '论文冲刺',
      week: 3,
      title: '限时论文：进度',
      estimatedMinutes: 120,
      content:
        '按考试节奏完成进度类论文。必须引用素材卡中的真实数字；可用 AI 做结构诊断，禁止代写经历。',
      path: ['抽题', '2 小时内完稿', '标注度量数字', '结构自检'],
      references: [ref('软考官网', RK)],
      acceptanceCriteria: ['完稿', '含≥3 个数字度量'],
      acceptanceTests: [
        ['e31', '用了哪张素材卡？', '指出'],
        ['e32', '三个数字是？', '列出'],
        ['e33', '不足与改进写了吗？', '是'],
      ],
      deliverable: '论文成稿1',
      track: 'practice',
      requireEvidence: true,
    },
    {
      phaseId: 'H3',
      phaseName: '论文冲刺',
      week: 3,
      title: '限时论文：风险',
      estimatedMinutes: 120,
      content:
        '完成风险类限时论文，强调识别-分析-应对-监控闭环，并写一次真实风险事件处理。',
      path: ['抽题', '完稿', '对照素材卡补细节', '删空话'],
      references: [ref('软考官网', RK)],
      acceptanceCriteria: ['完稿', '有风险事件闭环'],
      acceptanceTests: [
        ['e34', '主要风险是？', '具体'],
        ['e35', '应对策略？', '具体'],
        ['e36', '监控手段？', '具体'],
      ],
      deliverable: '论文成稿2',
      track: 'practice',
      requireEvidence: true,
    },
    {
      phaseId: 'H3',
      phaseName: '论文冲刺',
      week: 3,
      title: '缓冲日：论文提纲闪卡',
      track: 'rest',
      estimatedMinutes: 30,
      content:
        '两篇重论文后的轻量日。只过子标题闪卡与素材数字，不新开全文。为第三篇与后续模考留体力。',
      path: ['过子标题闪卡', '默写三套提纲关键词', '核对素材卡数字', '早点休息'],
      references: [ref('软考官网', RK)],
      acceptanceCriteria: ['闪卡完成', '未开新全文'],
      acceptanceTests: [
        ['e37r', '进度子标题能否默写？', '是/部分'],
        ['e38r', '今天是否写新全文？', '否'],
        ['e39r', '素材数字核对了吗？', '是'],
      ],
      deliverable: '提纲闪卡日志',
      minimumMode: true,
    },
    {
      phaseId: 'H3',
      phaseName: '论文冲刺',
      week: 3,
      title: '半程论文：质量/需求（提纲+半稿）',
      estimatedMinutes: 75,
      content:
        '第三篇不再连轴全长限时：完成完整提纲与不少于半稿（含数据点），其余可次日补。降低末段过载，仍保留可验收产物。',
      path: ['抽题列完整提纲', '写半稿含≥2 数据点', '标待补段落', '结构自检'],
      references: [ref('软考官网', RK)],
      acceptanceCriteria: ['提纲完整', '半稿含数据'],
      acceptanceTests: [
        ['e37', '核心质量/需求问题？', '具体'],
        ['e38', '数据指标？', '列出'],
        ['e39', '待补段落写清了吗？', '是'],
      ],
      deliverable: '论文半稿3',
      track: 'practice',
      requireEvidence: true,
    },
    {
      phaseId: 'H3',
      phaseName: '论文冲刺',
      week: 4,
      title: '节奏模考日（选择+案例，控时）',
      estimatedMinutes: 120,
      content:
        '按考试顺序演练耐力与切换，但不追求「一次考完全天」。模考后只复习错题与论文子标题，不再开新书。',
      path: ['选择限时', '案例限时', '复盘错题', '调整时间盒'],
      references: [ref('软考官网', RK)],
      acceptanceCriteria: ['完成模考', '时间盒结论成文'],
      acceptanceTests: [
        ['e40', '哪科超时？', '如实'],
        ['e41', '最大失分点？', '指出'],
        ['e42', '明日只复习什么？', '明确'],
      ],
      deliverable: '模考战报',
      track: 'practice',
      requireEvidence: true,
      minimumMode: true,
    },
    {
      phaseId: 'H3',
      phaseName: '论文冲刺',
      week: 4,
      title: '报名行政与准考证清单',
      track: 'admin',
      estimatedMinutes: 35,
      content:
        '把报名、照片、缴费、准考证、交通演练当成项目任务管理，防止因行政失误丢掉考试机会。',
      path: ['写行政清单', '设报名监视提醒', '准备证件照片', '规划考点交通'],
      references: [ref('软考官网', RK), ref('人社部', MOHRSS)],
      acceptanceCriteria: ['行政清单完整', '提醒已设'],
      acceptanceTests: [
        ['e43', '报名窗口怎么监视？', '说清'],
        ['e44', '证件是否有效？', '是'],
        ['e45', '交通预留多久？', '有数字'],
      ],
      deliverable: '行政清单',
      minimumMode: true,
    },
    {
      phaseId: 'H3',
      phaseName: '论文冲刺',
      week: 4,
      title: '门禁 G3：考前就绪验收',
      track: 'gate',
      gateId: 'G3',
      estimatedMinutes: 50,
      content:
        '确认三篇论文（含半稿补完计划）、模考战报、行政清单、公式卡全部就绪。此门禁通过才进入「只复习不新学」状态。',
      path: ['清点产物', '补缺口', '提交证据包', '写考前一周计划'],
      references: [ref('软考官网', RK)],
      acceptanceCriteria: ['产物齐', '考前计划有', '证据非空'],
      acceptanceTests: [
        ['g3a', '三篇论文题目方向？', '列出'],
        ['g3b', '行政最大风险？', '说出'],
        {
          id: 'g3c',
          question: '考前一周第一原则（打字）',
          passHint: '例如：不新学',
          requiresTypedAnswer: true,
        },
      ],
      deliverable: 'G3 考前包',
      requireEvidence: true,
      minimumMode: true,
    },
    {
      phaseId: 'H3',
      phaseName: '论文冲刺',
      week: 4,
      title: '考前只复习：错题+公式+子标题',
      estimatedMinutes: 45,
      content:
        '停止新内容。只复习错题本、公式卡与论文子标题，保证睡眠与作息，把状态管理纳入备考。与终验门禁之间保留此轻量日。',
      path: ['错题快刷', '公式默写', '子标题默写', '固定睡觉时间'],
      references: [ref('软考官网', RK)],
      acceptanceCriteria: ['三项复习完成', '作息写下'],
      acceptanceTests: [
        ['e46', '默写公式是否通过？', '是/否'],
        ['e47', '今晚几点睡？', '有时间'],
        ['e48', '是否打开新书？', '否'],
      ],
      deliverable: '考前复习日志',
      minimumMode: true,
    },
    {
      phaseId: 'H3',
      phaseName: '论文冲刺',
      week: 4,
      title: '轻量缓冲：准考证与作息核对',
      track: 'rest',
      estimatedMinutes: 20,
      content:
        'G3 与终验门禁之间的第二道缓冲。只核对准考证/证件/交通与睡眠计划，不做新模考，避免连轴高压。',
      path: ['核对准考证与证件', '确认交通预案', '写下睡觉时间', '收起新资料'],
      references: [ref('软考官网', RK), ref('人社部', MOHRSS)],
      acceptanceCriteria: ['证件核对完成', '作息写下'],
      acceptanceTests: [
        ['e46b', '准考证就绪？', '是/待打印'],
        ['e47b', '交通预案？', '有'],
        ['e48b', '今晚几点睡？', '有时间'],
      ],
      deliverable: '考前缓冲清单',
      minimumMode: true,
    },
    {
      phaseId: 'H3',
      phaseName: '论文冲刺',
      week: 4,
      title: '考试日/模拟考试日战报',
      estimatedMinutes: 150,
      content:
        '若非真实考试日，则按开考到结束完整模拟（可按科目分段）。战后写战报：时间分配、翻车点、若重来如何调整。强度低于旧版「连轴 210 分钟」设定。',
      path: ['按科目顺序模拟或参考', '记录时间盒', '写战报', '归档全部材料'],
      references: [ref('软考官网', RK)],
      acceptanceCriteria: ['战报完成', '材料归档'],
      acceptanceTests: [
        ['e49', '哪科最险？', '指出'],
        ['e50', '时间分配是否合理？', '结论'],
        ['e51', '归档路径？', '写出'],
      ],
      deliverable: '考试战报',
      requireEvidence: true,
      track: 'gate',
      gateId: 'GX',
      minimumMode: true,
    },
  ]),
};
