import type { CurriculumPack } from '../types/curriculum';
import { buildDaysFromDrafts, ref } from './dayFactory';

const RAP = 'https://help.sap.com/docs/abap-cloud/abap-rap';
const CDS = 'https://help.sap.com/docs/abap-cloud/abap-data-models';
const EXT = 'https://help.sap.com/docs/SAP_S4HANA_CLOUD/0f69f8fb28ac4bf48d2b57b9637e81fa';
const DEV = 'https://developers.sap.com/';
const LEARN = 'https://learning.sap.com/';

/**
 * SAP/ABAP skill pack for working professionals and career switchers.
 */
export const sapAbapPack: CurriculumPack = {
  id: 'skill-sap-abap',
  version: '2.0.0',
  title: 'SAP ABAP · S/4 扩展成长',
  subtitle: '在职/转行：RAP · Clean Core · 作品集门禁',
  category: 'skill',
  locale: 'zh-CN',
  supportedPersonTypes: [
    'working_professional',
    'career_switcher',
    'college_student',
    'exam_sprinter',
  ],
  summary:
    '从环境摸底到 RAP 闭环与 Clean Core 评估，面向企业 SAP 技术骨干路径。',
  optionFields: [
    {
      id: 'businessDomain',
      label: '主业务域',
      type: 'select',
      defaultValue: 'MM',
      options: [
        { value: 'MM', label: 'MM 采购' },
        { value: 'SD', label: 'SD 销售' },
        { value: 'FI', label: 'FI 财务' },
        { value: 'PP', label: 'PP 生产' },
      ],
    },
  ],
  optionalTracks: ['cert', 'side'],
  phases: [
    { id: 'A', name: '摸底', goal: '契约与环境就绪', gateId: 'M0' },
    { id: 'B', name: 'RAP筑基', goal: '可演示小应用', gateId: 'M1' },
    { id: 'C', name: 'Clean Core', goal: '评估文档', gateId: 'M2' },
    { id: 'D', name: '作品集', goal: '三案例打包', gateId: 'M3' },
  ],
  days: buildDaysFromDrafts([
    {
      phaseId: 'A',
      phaseName: '摸底',
      week: 1,
      title: '开营：建立知识库与学习契约',
      content:
        '明确 12 周内要成为「能做 S/4 扩展决策的 ABAP」；创建笔记目录；写下每周小时、放弃清单。今天不写业务代码，只装好学习操作系统。',
      path: [
        '创建 SAP-Growth 目录结构',
        '填写周小时与放弃清单',
        '设置日历提醒（至少 4 次）',
        '阅读本包阶段目标一页',
      ],
      references: [ref('SAP Developers', DEV), ref('SAP Learning', LEARN)],
      acceptanceCriteria: ['目录可截图', '契约含周小时数字', '日历提醒已建'],
      acceptanceTests: [
        ['a1', '你的每周主线小时数是？', '说出具体数字'],
        ['a2', '放弃清单至少两项？', '例如同时开多轨道/无效考证'],
        {
          id: 'a3',
          question: '用一句话写出你的终态定位',
          passHint: '至少 8 个字',
          requiresTypedAnswer: true,
        },
      ],
      deliverable: '学习契约.md',
      minimumMode: true,
    },
    {
      phaseId: 'A',
      phaseName: '摸底',
      week: 1,
      title: '技能盘点：24 个月能力雷达',
      content:
        '按报表/增强/接口/OO/CDS/RAP/Fiori/性能/权限盘点熟练度 1～5，并找出 3 个可写作品集的真实项目，禁止虚构经历。',
      path: [
        '列出 10 条代表性工作',
        '填熟练度表',
        '标出薄弱项 Top3',
        '选定 3 个项目素材标题',
      ],
      references: [ref('SAP Community', 'https://community.sap.com/')],
      acceptanceCriteria: ['10 类熟练度齐全', '3 个真实项目标题'],
      acceptanceTests: [
        ['a4', '熟练度≥4 的类别？', '能举例交付物'],
        ['a5', '最弱类别是？', '诚实标出'],
        ['a6', '三个素材项目名？', '可对应真实经历'],
      ],
      deliverable: '技能盘点.md',
      minimumMode: true,
    },
    {
      phaseId: 'A',
      phaseName: '摸底',
      week: 1,
      title: '环境档案：系统与扩展事实摸底',
      content:
        '写清 ECC/S4、是否 RISE、Fiori、BTP、中间件。未知必须写「待问+负责人」，禁止把未知当已知长期空着。',
      path: [
        '确认系统版本与客户机用途',
        '确认 Fiori/BTP/中间件有无',
        '向 Basis/架构发确认消息',
        '输出环境档案一页',
      ],
      references: [
        ref('S/4HANA', 'https://www.sap.com/products/erp/s4hana.html'),
        ref('BTP Trial', 'https://www.sap.com/products/technology-platform/trial.html'),
      ],
      acceptanceCriteria: ['档案字段填完或待问', '至少发出一条确认'],
      acceptanceTests: [
        ['a7', 'ECC 还是 S/4？', '明确或说明混合'],
        ['a8', '有无 BTP？', '有/无/待问含负责人'],
        ['a9', '中间件名称？', '能说出或待确认'],
      ],
      deliverable: '环境档案.md',
    },
    {
      phaseId: 'A',
      phaseName: '摸底',
      week: 1,
      title: '练习环境攻坚（必须可登录）',
      estimatedMinutes: 120,
      content:
        '优先级：公司沙箱 > 学习机 > Trial。若无法创建对象，必须写降级验收方案，否则后续 RAP 门禁不可虚假 Pass。',
      path: [
        '申请或登录练习系统',
        '验证可打开 ADT/SE80',
        '记录命名空间与权限限制',
        '失败则写 R1 风险与降级方案',
      ],
      references: [
        ref('ADT', 'https://tools.hana.ondemand.com/#abap'),
        ref('Developers', DEV),
      ],
      acceptanceCriteria: ['可登录或书面降级', '复现步骤清楚'],
      acceptanceTests: [
        ['a10', '今天能否创建/打开开发对象？', '是或有工单号'],
        ['a11', '使用的工具？', 'ADT/SE80/其它'],
        ['a12', '包/命名空间规则？', '能说出要点'],
      ],
      deliverable: '环境就绪证明或降级说明',
      requireEvidence: true,
    },
    {
      phaseId: 'A',
      phaseName: '摸底',
      week: 1,
      title: '门禁 M0：摸底验收',
      track: 'gate',
      gateId: 'M0',
      content:
        '对照契约、盘点、环境、练习机状态做一次正式门禁。未完成项只能结转或降级书面化，不可假装完成。',
      path: [
        '勾选 M0 清单',
        '上传/填写证据（截图路径）',
        '写下阶段 B 的 Top3',
        '更新风险登记',
      ],
      references: [ref('RAP 预读', RAP)],
      acceptanceCriteria: ['M0 全处理', '证据非空', 'Top3 明确'],
      acceptanceTests: [
        ['m0a', '练习环境状态？', '就绪或降级'],
        ['m0b', '证据写了什么？', '路径/截图说明'],
        {
          id: 'm0c',
          question: '阶段 B 第一优先级（打字）',
          passHint: '例如：三种扩展对比',
          requiresTypedAnswer: true,
        },
      ],
      deliverable: 'M0 验收记录',
      minimumMode: true,
      requireEvidence: true,
    },
    {
      phaseId: 'B',
      phaseName: 'RAP筑基',
      week: 2,
      title: '三种扩展方式对比（Clean Core 语境）',
      content:
        '建立 Key User / Developer / Side-by-side 决策语言，并用一个公司真实需求做归类，避免只会背名词。',
      path: [
        '阅读 Extensibility 概述',
        '做三列对比表',
        '选一个真实需求归类',
        '写出禁止做法（改标准码等）',
      ],
      references: [ref('Extensibility', EXT), ref('Developers', DEV)],
      acceptanceCriteria: ['对比表含适用/不适用', '至少一个需求已归类'],
      acceptanceTests: [
        ['b1', 'Key User 典型能力？', '字段/轻逻辑等'],
        ['b2', 'Side-by-side 常见落点？', 'BTP 等'],
        ['b3', '改标准程序策略？', '不推荐/禁止'],
      ],
      deliverable: '三种扩展对比表',
      minimumMode: true,
    },
    {
      phaseId: 'B',
      phaseName: 'RAP筑基',
      week: 2,
      title: 'RAP 分层心智模型与术语表',
      content:
        '完成公开课/文档导读，画清数据/行为/服务分层，并建立至少 25 个中英术语，为 CDS/Behavior 动手做准备。',
      path: [
        '打开 Learning/Help RAP 入口',
        '画分层图',
        '建立术语表≥25',
        '录音或默讲 3 分钟',
      ],
      references: [ref('RAP Help', RAP), ref('Learning', LEARN)],
      acceptanceCriteria: ['分层图可讲', '术语≥25'],
      acceptanceTests: [
        ['b4', '行为放哪一层？', 'Behavior'],
        ['b5', 'Projection 用途？', '裁剪/消费视角'],
        ['b6', '说出 5 个术语', '不看表能说'],
      ],
      deliverable: '分层图 + 术语表',
      minimumMode: true,
    },
    {
      phaseId: 'B',
      phaseName: 'RAP筑基',
      week: 2,
      title: 'CDS View Entity 第一个可激活对象',
      content:
        '在练习环境创建并激活第一个 view entity；若环境降级，则完成等价设计文档并标注阻塞，不得空 Pass。',
      path: [
        '阅读 CDS View Entity 章节',
        '创建练习包对象',
        '激活并记录报文',
        '写字段说明 5 条',
      ],
      references: [ref('CDS', CDS), ref('RAP', RAP)],
      acceptanceCriteria: ['对象激活或设计降级完备', '有字段说明'],
      acceptanceTests: [
        ['b7', '对象名是？', '写出'],
        ['b8', '关键键字段？', '能指出'],
        ['b9', '卡点与解决？', '有记录或无卡点'],
      ],
      deliverable: 'CDS 练习对象/设计稿',
      requireEvidence: true,
    },
    {
      phaseId: 'B',
      phaseName: 'RAP筑基',
      week: 2,
      title: 'Association / Composition 差异精练',
      content:
        '用自己的话区分 association 与 composition，并在模型草图中各举一例，服务后续 BO 子实体设计。',
      path: [
        '精读关联章节',
        '画模型草图',
        '写差异对照 6 条',
        '对照公司业务选父子关系一例',
      ],
      references: [ref('CDS', CDS)],
      acceptanceCriteria: ['差异对照成文', '草图含两类关系'],
      acceptanceTests: [
        ['b10', 'composition 对删除语义影响？', '合理表述'],
        ['b11', '你的业务父子例？', '具体'],
        ['b12', '为何 RAP 子实体常用 composition？', '合理'],
      ],
      deliverable: '关联差异笔记',
    },
    {
      phaseId: 'B',
      phaseName: 'RAP筑基',
      week: 3,
      title: '投影视图与常用注解速查',
      content:
        '完成投影裁剪，并整理 ≥20 条常用注解（UI/Consumption/Access 等），每条写「何时用」避免机械堆积。',
      path: [
        '创建投影视图',
        '添加基础 UI 注解',
        '整理速查表≥20',
        '预览或文档化预览步骤',
      ],
      references: [ref('CDS', CDS), ref('RAP', RAP)],
      acceptanceCriteria: ['速查表≥20', '投影可说明用途'],
      acceptanceTests: [
        ['b13', '为何要投影？', '裁剪/场景化'],
        ['b14', '举 3 个注解名', '正确'],
        ['b15', 'Access Control 解决什么？', '行级权限等'],
      ],
      deliverable: '注解速查表',
      minimumMode: true,
    },
    {
      phaseId: 'B',
      phaseName: 'RAP筑基',
      week: 3,
      title: 'Behavior：BO 骨架与 CRUD 幸福路径',
      estimatedMinutes: 100,
      content:
        '创建业务对象骨架并实现 create/update（或 delete）幸福路径；用测试表记录正例与至少 2 个负例，形成可回归证据。',
      path: [
        '定义 Behavior Definition',
        '实现 create',
        '实现 update 或 delete',
        '填写测试表（正+负）',
      ],
      references: [ref('RAP', RAP)],
      acceptanceCriteria: ['可演示至少创建', '测试表存在'],
      acceptanceTests: [
        ['b16', 'BO 根实体名？', '写出'],
        ['b17', '负例测了什么？', '举例'],
        ['b18', '失败消息是否可懂？', '是/改进点'],
      ],
      deliverable: 'BO CRUD 证据',
      requireEvidence: true,
    },
    {
      phaseId: 'B',
      phaseName: 'RAP筑基',
      week: 3,
      title: '校验/确定 + 服务暴露',
      content:
        '至少两条 validation 与一条 determination；完成 Service Definition/Binding，并写出权限设计草稿（即使尚未完全配置）。',
      path: [
        '实现 2 条校验',
        '实现 1 条确定',
        '绑定服务并预览',
        '写权限角色草稿',
      ],
      references: [ref('RAP', RAP)],
      acceptanceCriteria: ['校验可触发失败提示', '服务可访问或步骤完备'],
      acceptanceTests: [
        ['b19', '校验规则业务含义？', '说清'],
        ['b20', '服务协议/绑定类型？', '能说出'],
        ['b21', '权限草稿含哪些角色？', '至少 1 个'],
      ],
      deliverable: '服务+校验+权限草稿',
      requireEvidence: true,
    },
    {
      phaseId: 'B',
      phaseName: 'RAP筑基',
      week: 3,
      title: '门禁 M1：RAP 演示验收',
      track: 'gate',
      gateId: 'M1',
      estimatedMinutes: 120,
      content:
        '正式演示 RAP 小应用：功能、校验、服务、README、对比文（经典 vs RAP）。无证据不得 Pass。录制或逐字稿均可。',
      path: [
        '按 README 复现一遍',
        '录制 8～10 分钟讲解或写逐字稿',
        '提交对比文≥600 字要点',
        '填写 M1 打分表',
      ],
      references: [ref('RAP', RAP), ref('Learning', LEARN)],
      acceptanceCriteria: ['可复现', '讲解存在', '证据完备'],
      acceptanceTests: [
        ['m1a', '演示对象名？', '写出'],
        ['m1b', '两条校验是什么？', '列出'],
        {
          id: 'm1c',
          question: '经典实现相对 RAP 的最大差异（打字）',
          passHint: '至少 15 字',
          requiresTypedAnswer: true,
        },
      ],
      deliverable: 'M1 演示包',
      minimumMode: true,
      requireEvidence: true,
    },
    {
      phaseId: 'C',
      phaseName: 'Clean Core',
      week: 4,
      title: '脏核心清单与 A/B/C/D 分级',
      content:
        '把公司自定义扩到可评审清单，按清洁/可接受/不推荐/未知分级，并为每条附证据（传输号/对象名）。',
      path: [
        '收集 ≥15 条自定义',
        '定义本地分级标准',
        '完成初分',
        '标出 Top5 风险',
      ],
      references: [
        ref('Extensibility', EXT),
        ref('Community Clean Core', 'https://community.sap.com/?q=clean%20core'),
      ],
      acceptanceCriteria: ['≥15 条含证据', 'Top5 可讲解'],
      acceptanceTests: [
        ['c1', '分级标准四类？', '能复述'],
        ['c2', 'Top1 风险对象？', '有名'],
        ['c3', '证据字段示例？', '传输号等'],
      ],
      deliverable: '脏核心清单 v1',
      requireEvidence: true,
    },
    {
      phaseId: 'C',
      phaseName: 'Clean Core',
      week: 4,
      title: '同一需求三种扩展故事',
      content:
        '选同一业务需求，分别写 Key User / on-stack 开发 / side-by-side 三条路径，比较成本、升级风险与适用边界。',
      path: [
        '选定需求',
        '写三条路径各 300+ 字要点',
        '做决策推荐',
        '请同事或自己做红队质疑',
      ],
      references: [ref('Extensibility', EXT)],
      acceptanceCriteria: ['三路径成文', '有明确推荐'],
      acceptanceTests: [
        ['c4', '推荐哪条？为何？', '有理由'],
        ['c5', '哪条升级风险最高？', '说清'],
        ['c6', '红队提出的反例？', '有记录'],
      ],
      deliverable: '三路径故事文',
    },
    {
      phaseId: 'C',
      phaseName: 'Clean Core',
      week: 4,
      title: '集成族谱与检查清单',
      content:
        '盘点入站/出站接口族谱，并沉淀幂等、重试、对账、超时等非功能检查清单，直接可用于接口评审。',
      path: [
        '设计族谱字段',
        '登记 ≥8 条接口',
        '写检查清单 10 条',
        '画一条现状序列图',
      ],
      references: [
        ref('Integration Suite', 'https://help.sap.com/docs/cloud-integration'),
        ref('Event Mesh', 'https://help.sap.com/docs/sap-event-mesh'),
      ],
      acceptanceCriteria: ['族谱≥8', '清单≥10', '有序列图'],
      acceptanceTests: [
        ['c7', '最脆接口是？', '指出'],
        ['c8', '幂等怎么做？', '业务键层表述'],
        ['c9', '对账有无？', '有/无+计划'],
      ],
      deliverable: '接口族谱+检查清单',
      requireEvidence: true,
    },
    {
      phaseId: 'C',
      phaseName: 'Clean Core',
      week: 4,
      title: '门禁 M2：Clean Core 评估文档',
      track: 'gate',
      gateId: 'M2',
      estimatedMinutes: 120,
      content:
        '交付可给架构师审阅的评估 v1.0：范围、方法、发现、Top5、路线图、风险。必须附证据与反馈记录。',
      path: [
        '拼装文档章节',
        '补 Top5 工作量粗估',
        '请一人给反馈',
        '归档 v1.0',
      ],
      references: [ref('Extensibility', EXT)],
      acceptanceCriteria: ['文档完整', '有反馈', '证据非空'],
      acceptanceTests: [
        ['m2a', 'Top1 改造建议？', '说清'],
        ['m2b', '90 天路线做什么？', '列出'],
        {
          id: 'm2c',
          question: '文档存放路径（打字）',
          passHint: '文件路径或链接',
          requiresTypedAnswer: true,
        },
      ],
      deliverable: 'CleanCore_v1.0',
      minimumMode: true,
      requireEvidence: true,
    },
    {
      phaseId: 'D',
      phaseName: '作品集',
      week: 5,
      title: '业务域单据流精读（按开营域）',
      content:
        '按你选择的业务域，画端到端单据流与异常分支，并能用 10 分钟向非开发同事讲清系统落点。',
      path: [
        '选主域链路',
        '跟一笔真实单据',
        '画流转图',
        '写异常分支≥3',
      ],
      references: [ref('SAP Help', 'https://help.sap.com/')],
      acceptanceCriteria: ['流转图可讲', '异常分支≥3'],
      acceptanceTests: [
        ['d1', '主域是？', '与设置一致'],
        ['d2', '关键单据节点？', '列出'],
        ['d3', '一个业务异常例子？', '具体'],
      ],
      deliverable: '业务流转图',
      minimumMode: true,
    },
    {
      phaseId: 'D',
      phaseName: '作品集',
      week: 5,
      title: '增强点地图与迁移建议',
      content:
        '梳理该业务链常见增强点≥8，并与 Clean Core 分级交叉，给出每点迁移建议（保留/替换/旁路）。',
      path: [
        '列增强点≥8',
        '交叉 Clean Core 级别',
        '写迁移建议',
        '标出不可碰的合规点',
      ],
      references: [
        ref('Community', 'https://community.sap.com/'),
        ref('Extensibility', EXT),
      ],
      acceptanceCriteria: ['地图≥8', '每点有建议'],
      acceptanceTests: [
        ['d4', '举 3 个增强点', '有名'],
        ['d5', '哪个必须 side-by-side？', '有理由'],
        ['d6', '哪个可暂留？', '有理由'],
      ],
      deliverable: '增强点地图',
      requireEvidence: true,
    },
    {
      phaseId: 'D',
      phaseName: '作品集',
      week: 5,
      title: '组装作品集三案例',
      estimatedMinutes: 100,
      content:
        '把 RAP 演示、Clean Core 评估、集成/业务方案脱敏打包为作品集，含定位句与 README，达到可述职水平。',
      path: [
        '建 portfolio README',
        '放入案例 1/2/3',
        '写定位句',
        '做一次陌生人走查',
      ],
      references: [ref('Developers', DEV)],
      acceptanceCriteria: ['三案例齐全', '有走查问题列表'],
      acceptanceTests: [
        ['d7', '定位句是？', '能背'],
        ['d8', '三案例标题？', '列出'],
        ['d9', '走查出的问题？', '至少 1 条'],
      ],
      deliverable: 'portfolio v1',
      requireEvidence: true,
    },
    {
      phaseId: 'D',
      phaseName: '作品集',
      week: 5,
      title: '门禁 M3：作品集与述职预演',
      track: 'gate',
      gateId: 'M3',
      estimatedMinutes: 120,
      content:
        '20 分钟述职结构预演：问题→方法→成果→诉求。门禁以作品集证据与讲稿完整为准。',
      path: [
        '写 20 分钟讲稿',
        '彩排并计时',
        '归档作品集路径',
        '列出希望接手的项目类型',
      ],
      references: [ref('SAP Community', 'https://community.sap.com/')],
      acceptanceCriteria: ['讲稿完整', '彩排记录', '证据非空'],
      acceptanceTests: [
        ['m3a', '述职开场定位句？', '能说'],
        ['m3b', '诉求是什么？', '项目类型'],
        {
          id: 'm3c',
          question: '作品集路径（打字）',
          passHint: '文件夹或链接',
          requiresTypedAnswer: true,
        },
      ],
      deliverable: 'M3 述职包',
      minimumMode: true,
      requireEvidence: true,
    },
  ]),
};
