import type { CurriculumPack } from '../types/curriculum';
import { buildDaysFromDrafts, ref } from './dayFactory';

const MDN = 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript';
const TS = 'https://www.typescriptlang.org/docs/handbook/intro.html';
const TS_EVERYDAY = 'https://www.typescriptlang.org/docs/handbook/2/everyday-types.html';

/**
 * TypeScript foundations skill pack for multiple age/energy profiles.
 */
export const skillTypescriptPack: CurriculumPack = {
  id: 'skill-typescript-basics',
  version: '1.0.0',
  title: 'TypeScript 基础 21 天',
  subtitle: '语法 → 小项目 → 可读类型',
  category: 'skill',
  locale: 'zh-CN',
  supportedPersonTypes: [
    'teen_student',
    'college_student',
    'working_professional',
    'career_switcher',
    'senior_learner',
  ],
  summary: '适合从 JavaScript 过渡到 TypeScript 的通用技能包，强调可运行小练习与验收。',
  phases: [
    { id: 'T1', name: 'JS现代基础', goal: '异步与模块过关', gateId: 'T-G1' },
    { id: 'T2', name: 'TS类型系统', goal: '日常类型熟练', gateId: 'T-G2' },
    { id: 'T3', name: '小项目', goal: '可演示工具', gateId: 'T-G3' },
  ],
  days: buildDaysFromDrafts([
    {
      phaseId: 'T1',
      phaseName: 'JS现代基础',
      week: 1,
      title: '环境：Node/浏览器任选可运行',
      content:
        '选一个可运行环境（Node 或浏览器控制台+本地 HTML）。今天目标是「改一行代码能立刻看到结果」，降低后续学习摩擦。',
      path: ['安装或确认运行环境', '运行 Hello', '记录启动命令', '建练习文件夹'],
      references: [ref('MDN JavaScript', MDN), ref('TypeScript Handbook', TS)],
      acceptanceCriteria: ['能运行 Hello', '启动步骤可复现'],
      acceptanceTests: [
        ['t1', '你用的环境？', 'Node/浏览器'],
        ['t2', '启动命令/方式？', '写出'],
        ['t3', '练习目录路径？', '写出'],
      ],
      deliverable: '环境说明.md',
      minimumMode: true,
      requireEvidence: true,
    },
    {
      phaseId: 'T1',
      phaseName: 'JS现代基础',
      week: 1,
      title: 'let/const、解构与模块',
      content:
        '掌握现代绑定与模块导入导出，避免再写依赖全局变量的脚本。完成一个分成两个文件的小例子。',
      path: ['阅读 MDN 模块章节', '写两文件互调', '用 const 重构变量', '总结 5 条规范'],
      references: [ref('MDN 模块', 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Guide/Modules')],
      acceptanceCriteria: ['两文件示例可运行', '规范 5 条'],
      acceptanceTests: [
        ['t4', '为何少用 var？', '合理'],
        ['t5', 'export 了什么？', '指出'],
        ['t6', '解构例子？', '写出'],
      ],
      deliverable: 'modules-demo',
    },
    {
      phaseId: 'T1',
      phaseName: 'JS现代基础',
      week: 1,
      title: 'Promise 与 async/await',
      content:
        '把回调心智升级为 Promise/async。写一个模拟延迟任务并正确处理成功与失败分支。',
      path: ['读 MDN Promise', '写 delay 函数', '写失败分支', '对比 then 与 await'],
      references: [ref('MDN Promise', 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise')],
      acceptanceCriteria: ['成功失败都能演示', '有对比笔记'],
      acceptanceTests: [
        ['t7', 'await 只能用在哪？', 'async 函数等'],
        ['t8', '如何捕获失败？', 'try/catch'],
        ['t9', '演示怎么跑？', '说步骤'],
      ],
      deliverable: 'async-demo',
      minimumMode: true,
    },
    {
      phaseId: 'T1',
      phaseName: 'JS现代基础',
      week: 1,
      title: '门禁 T-G1：JS 现代基础验收',
      track: 'gate',
      gateId: 'T-G1',
      content:
        '提交可运行仓库/文件夹：模块示例 + 异步示例 + README。证明你具备进入 TypeScript 的地板能力。',
      path: ['整理 README', '自测复现', '录 3 分钟讲解或写步骤', '提交证据路径'],
      references: [ref('MDN', MDN)],
      acceptanceCriteria: ['两示例可复现', 'README 完整'],
      acceptanceTests: [
        ['tg1a', '如何运行模块示例？', '步骤'],
        ['tg1b', '异步失败怎么演示？', '步骤'],
        {
          id: 'tg1c',
          question: '项目路径（打字）',
          passHint: '文件夹路径',
          requiresTypedAnswer: true,
        },
      ],
      deliverable: 'T-G1 包',
      requireEvidence: true,
      minimumMode: true,
    },
    {
      phaseId: 'T2',
      phaseName: 'TS类型系统',
      week: 2,
      title: '安装 TypeScript 并编译第一行',
      content:
        '初始化 tsconfig，写第一个 .ts 文件并编译/运行。搞清 type check 与 emit 的基本关系。',
      path: ['安装 typescript', '写 tsconfig', '编译 Hello', '记录常用命令'],
      references: [ref('TS Handbook', TS)],
      acceptanceCriteria: ['可编译', '命令记录齐'],
      acceptanceTests: [
        ['t10', 'tsc 命令？', '写出'],
        ['t11', 'tsconfig 目的？', '合理'],
        ['t12', '输出目录？', '指出'],
      ],
      deliverable: 'ts-hello',
      requireEvidence: true,
      minimumMode: true,
    },
    {
      phaseId: 'T2',
      phaseName: 'TS类型系统',
      week: 2,
      title: 'Everyday Types：原始类型与对象',
      content:
        '练习 string/number/boolean/array/object 注解，体会类型缩小错误空间。完成 10 个小断言练习。',
      path: ['读 Everyday Types', '做 10 题练习', '故意写错看报错', '整理笔记'],
      references: [ref('Everyday Types', TS_EVERYDAY)],
      acceptanceCriteria: ['10 题完成', '有报错截图或记录'],
      acceptanceTests: [
        ['t13', '数组两种写法？', '能说'],
        ['t14', '可选属性语法？', '?:'],
        ['t15', '今天最有用的报错？', '举例'],
      ],
      deliverable: 'everyday-notes',
    },
    {
      phaseId: 'T2',
      phaseName: 'TS类型系统',
      week: 2,
      title: '接口 interface 与类型别名',
      content:
        '用 interface 描述数据结构，用 type 做联合/交叉入门。把一个 JSON 配置描述成类型。',
      path: ['定义 User 接口', '定义联合状态类型', '给配置文件加类型', '写 5 条选用原则'],
      references: [ref('Object Types', 'https://www.typescriptlang.org/docs/handbook/2/objects.html')],
      acceptanceCriteria: ['配置类型可用', '原则 5 条'],
      acceptanceTests: [
        ['t16', 'interface 例？', '写出'],
        ['t17', '联合类型例？', '写出'],
        ['t18', '何时用 type？', '合理'],
      ],
      deliverable: 'types-config',
      minimumMode: true,
    },
    {
      phaseId: 'T2',
      phaseName: 'TS类型系统',
      week: 2,
      title: '函数类型与泛型入门',
      content:
        '为函数参数/返回值标注类型，并写一个最小泛型函数（如 identity 或 wrap）。理解泛型是「延迟决定类型」。',
      path: ['标注 3 个函数', '写 identity 泛型', '用在数组工具函数', '总结易错点'],
      references: [ref('Generics', 'https://www.typescriptlang.org/docs/handbook/2/generics.html')],
      acceptanceCriteria: ['泛型函数可编译', '易错点≥3'],
      acceptanceTests: [
        ['t19', '泛型一句话？', '合理'],
        ['t20', '你的泛型函数名？', '写出'],
        ['t21', '一个易错点？', '举例'],
      ],
      deliverable: 'generics-mini',
    },
    {
      phaseId: 'T2',
      phaseName: 'TS类型系统',
      week: 2,
      title: '门禁 T-G2：类型系统小测',
      track: 'gate',
      gateId: 'T-G2',
      content:
        '闭卷完成 8 题类型标注小测，并提交你的类型练习仓库。通过才进入小项目周。',
      path: ['做小测 8 题', '整理仓库', '写 README', '提交证据'],
      references: [ref('Handbook', TS)],
      acceptanceCriteria: ['小测完成', '仓库可打开'],
      acceptanceTests: [
        ['tg2a', '小测得分感？', '如实'],
        ['tg2b', '最难题是？', '指出'],
        {
          id: 'tg2c',
          question: '仓库路径（打字）',
          passHint: '路径',
          requiresTypedAnswer: true,
        },
      ],
      deliverable: 'T-G2 包',
      requireEvidence: true,
      minimumMode: true,
    },
    {
      phaseId: 'T3',
      phaseName: '小项目',
      week: 3,
      title: '立项：做一个命令行小工具',
      content:
        '选定小工具主题（待办、单词本、番茄钟日志等），写清输入输出与非目标，避免做成大而无当。',
      path: ['选题', '写一页规格', '列非目标', '拆 3 日任务'],
      references: [ref('TS', TS)],
      acceptanceCriteria: ['规格一页', '非目标明确'],
      acceptanceTests: [
        ['t22', '主题？', '说出'],
        ['t23', '输入输出？', '说清'],
        ['t24', '明确不做？', '列出'],
      ],
      deliverable: 'spec.md',
      minimumMode: true,
    },
    {
      phaseId: 'T3',
      phaseName: '小项目',
      week: 3,
      title: '实现核心路径（可读类型）',
      estimatedMinutes: 90,
      content:
        '实现主路径，类型要表达业务状态，而不是 any 逃生。保证至少一条完整用户故事可跑通。',
      path: ['建模型类型', '实现主流程', '去掉 any', '手工测试 3 案'],
      references: [ref('Everyday Types', TS_EVERYDAY)],
      acceptanceCriteria: ['主故事可跑', '无 any（或极少并注释）'],
      acceptanceTests: [
        ['t25', '核心类型名？', '写出'],
        ['t26', '三条测试案？', '列出'],
        ['t27', 'any 还在吗？', '否或说明'],
      ],
      deliverable: 'core-feature',
      requireEvidence: true,
    },
    {
      phaseId: 'T3',
      phaseName: '小项目',
      week: 3,
      title: '错误处理与 README',
      content:
        '补齐失败路径与使用说明，让陌生人能按 README 在 5 分钟内跑起来。这是作品集门禁的关键。',
      path: ['补错误分支', '写 README', '让朋友按文档试跑或自演', '修文档洞'],
      references: [ref('TS', TS)],
      acceptanceCriteria: ['README 可复现', '失败路径可演示'],
      acceptanceTests: [
        ['t28', '失败如何表现？', '说出'],
        ['t29', 'README 第一步？', '说出'],
        ['t30', '试跑反馈？', '有'],
      ],
      deliverable: 'README完善',
      minimumMode: true,
    },
    {
      phaseId: 'T3',
      phaseName: '小项目',
      week: 3,
      title: '门禁 T-G3：小项目演示验收',
      track: 'gate',
      gateId: 'T-G3',
      estimatedMinutes: 100,
      content:
        '演示工具：讲清问题、类型设计、主路径与限制。提交仓库路径与 5 分钟讲稿/录屏说明。',
      path: ['彩排 5 分钟', '整理限制列表', '提交证据', '写下一步改进'],
      references: [ref('Handbook', TS)],
      acceptanceCriteria: ['可演示', '限制列表有', '证据非空'],
      acceptanceTests: [
        ['tg3a', '解决什么问题？', '一句话'],
        ['tg3b', '类型设计亮点？', '一点'],
        {
          id: 'tg3c',
          question: '仓库或演示路径（打字）',
          passHint: '路径/链接',
          requiresTypedAnswer: true,
        },
      ],
      deliverable: 'T-G3 演示包',
      requireEvidence: true,
      minimumMode: true,
    },
    {
      phaseId: 'T3',
      phaseName: '小项目',
      week: 3,
      title: '复盘：类型给协作带来的价值',
      content:
        '写短复盘：哪些报错提前拦住了 bug，哪些类型设计过度。形成可迁移到工作项目的原则卡片。',
      path: ['写复盘 400 字', '提炼原则 5 条', '列出下个练习主题', '归档'],
      references: [ref('TS', TS), ref('MDN', MDN)],
      acceptanceCriteria: ['复盘成文', '原则 5 条'],
      acceptanceTests: [
        ['t31', '一条原则？', '说出'],
        ['t32', '一个过度设计例子？', '有'],
        ['t33', '下一主题？', '有'],
      ],
      deliverable: '复盘.md',
      minimumMode: true,
    },
    {
      phaseId: 'T3',
      phaseName: '小项目',
      week: 3,
      title: '加餐：读一段开源 TS 类型',
      content:
        '阅读一个小型开源库的类型定义（或官方示例），记录 3 个看不懂后查懂的点，训练阅读真实代码能力。',
      path: ['选仓库/示例', '读类型定义', '记录 3 个疑问与答案', '分享笔记'],
      references: [
        ref('TypeScript Examples', 'https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes.html'),
      ],
      acceptanceCriteria: ['3 个疑问闭环', '笔记可分享'],
      acceptanceTests: [
        ['t34', '读的是什么？', '指出'],
        ['t35', '一个疑问？', '说出'],
        ['t36', '答案来源？', '文档/推断'],
      ],
      deliverable: '阅读笔记',
      track: 'side',
    },
    {
      phaseId: 'T3',
      phaseName: '小项目',
      week: 3,
      title: '缓冲补债日',
      content:
        '专用于补齐未 Pass 的任务。若已全部 Pass，则重构小项目命名与文件夹结构，提升作品集观感。',
      path: ['筛选 Fail/Partial', '逐项补验收', '或重构结构', '更新 README'],
      references: [ref('TS', TS)],
      acceptanceCriteria: ['无未处理失败或有计划', 'README 最新'],
      acceptanceTests: [
        ['t37', '失败项数？', '数字'],
        ['t38', '今天补了哪项？', '指出'],
        ['t39', '是否可展示？', '是/否'],
      ],
      deliverable: '补债记录',
      track: 'review',
      minimumMode: true,
    },
    {
      phaseId: 'T3',
      phaseName: '小项目',
      week: 3,
      title: '作品集包装与对外一句话',
      content:
        '把项目写成作品集条目：问题、方案、技术栈、链接、局限。练就面试/述职可用的 30 秒介绍。',
      path: ['写作品集条目', '练 30 秒介绍', '请人听一遍', '按反馈改'],
      references: [ref('TS', TS)],
      acceptanceCriteria: ['条目完整', '30 秒可讲'],
      acceptanceTests: [
        ['t40', '30 秒介绍？', '能讲'],
        ['t41', '局限写了吗？', '是'],
        ['t42', '反馈是什么？', '有'],
      ],
      deliverable: '作品集条目',
      minimumMode: true,
    },
    {
      phaseId: 'T3',
      phaseName: '小项目',
      week: 3,
      title: '结营：技能迁移清单',
      content:
        '列出把 TS 迁移到工作/学业的 5 个下一步（例如给旧 JS 模块补类型、在业务项目开严格模式等）。',
      path: ['写迁移清单 5 条', '标优先级', '设第一周行动', '归档全包'],
      references: [ref('TS Handbook', TS)],
      acceptanceCriteria: ['5 条清单', '有第一周行动'],
      acceptanceTests: [
        ['t43', '第一条行动？', '具体'],
        ['t44', '优先级第一？', '指出'],
        ['t45', '归档位置？', '写出'],
      ],
      deliverable: '迁移清单',
      track: 'gate',
      gateId: 'T-END',
      requireEvidence: true,
      minimumMode: true,
    },
    {
      phaseId: 'T3',
      phaseName: '小项目',
      week: 3,
      title: '休息日：仅复习闪卡',
      track: 'rest',
      estimatedMinutes: 25,
      content:
        '只复习类型术语闪卡（interface/type/union/generics/async）。低强度保持记忆连续性，适合疲惫日。',
      path: ['过闪卡 15 分钟', '默写 5 个定义', '记录遗忘项'],
      references: [ref('Everyday Types', TS_EVERYDAY)],
      acceptanceCriteria: ['闪卡完成', '遗忘项记录'],
      acceptanceTests: [
        ['t46', 'union 是什么？', '正确'],
        ['t47', 'generic 是什么？', '正确'],
        ['t48', '遗忘项？', '列出或无'],
      ],
      deliverable: '闪卡日志',
      minimumMode: true,
    },
    {
      phaseId: 'T3',
      phaseName: '小项目',
      week: 3,
      title: '可选：为小项目加测试',
      track: 'side',
      content:
        '若有余力，为核心函数加最小测试（任意测试框架或断言脚本）。把「可验证」当成技能标准的一部分。',
      path: ['选 2 个纯函数', '加断言/测试', '接入 npm script', '更新 README'],
      references: [ref('TS', TS)],
      acceptanceCriteria: ['至少 2 个测试', 'README 含测试命令'],
      acceptanceTests: [
        ['t49', '测试命令？', '写出'],
        ['t50', '测了什么？', '列出'],
        ['t51', '失败时如何看？', '说清'],
      ],
      deliverable: 'tests',
      requireEvidence: true,
    },
  ]),
};
